// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoApi1.Context;

#nullable disable

namespace ProjetoApi1.Migrations
{
    [DbContext(typeof(ProdutoContext))]
    [Migration("20240415003647_CriacaoTabelaProduto")]
    partial class CriacaoTabelaProduto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoApi1.Entities.TABELA_PRODUTO", b =>
                {
                    b.Property<int>("CODIGO_PRODUTO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CODIGO_PRODUTO"));

                    b.Property<string>("NOME_PRODUTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PRECO_PRODUTO")
                        .HasColumnType("float");

                    b.Property<double>("QUANTIDADE_PRODUTO")
                        .HasColumnType("float");

                    b.Property<string>("SITUACAO_PRODUTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CODIGO_PRODUTO");

                    b.ToTable("TABELA_PRODUTOS");
                });
#pragma warning restore 612, 618
        }
    }
}
